### ISSUE TITLE
Issue: embeds.js messageDeleted & messageEdited max size

### ISSUE THREAD

**Issue by kchaney1508** [devdeem/Logger-Bot#22]
Howdy. According to https://discordjs.guide/popular-topics/embeds.html#embed-limits, the max size of addFields is 1024. This would cause a fatal error when large messages would be edited or deleted. This is quickly fixed by moving ${message} into the setDescription. Not putting in a pull request, but that's the fix. I'm working on pushing it to my fork.

**Comment by devdeem** [comment]
Hello @kchaney1508, thank you for your feedback/issue, I am aware of this but I am no longer actively editing the code of this respository so feel free to fork this repo and edit everything etc...  But don't forget that you have to put a link to this original repository in the README of your repo, good luck and thanks!

**Comment by kchaney1508** [comment]
Done, and done. https://github.com/devdeem/Logger-Bot/pull/23
